name: Punishments
version: 1.2
main: me.brooklynsuperior.punishments.Punishments
authors: [speediv]
description: punishments that aren't vanilla punishments

commands:
  ban:
    description: Bans a player with said reason
    usage: /<command> [player] [reason]
  kick:
    description: Kicks a player with said reason
    usage: /<command> [player] [reason]
  unban:
    description: Unbans said player
    usage: /<command> [player]
    aliases: [pardon]
  warn:
    description: Warns a player with said reason
    usage: /<command> [player] [reason]
  mute:
    description: Mutes a player, also provides reason
    usage: /<command> [player] [reason]
  unmute:
    description: Unmutes said player
    usage: /<command> [player]
  punish:
    description: '"Punishes" a player'
    usage: /<command> [player] [reason]
  punishments:
    description: Gives you a list of all punishments
    usage: /<command>