name: Punishments
version: ${project.version}
main: me.totalfreedom.punishments.Punishments
authors: [speed]
description: Punishments plugin for the TotalFreedom SMP server
commands:
  ban:
    description: Bans a player, optionally with a reason
    usage: /<command> <player> [reason]
  kick:
    description: Kicks a player, optionally with a reason
    usage: /<command> <player> [reason]
  unban:
    description: Unbans a player
    usage: /<command> <player>
    aliases: [pardon]
  warn:
    description: Warns a player with a reason
    usage: /<command> <player> <reason>
  mute:
    description: Mutes a player, optionally with a reason
    usage: /<command> <player> [reason]
  unmute:
    description: Unmutes a player
    usage: /<command> <player>
  punish:
    description: Smite a player
    usage: /<command> <player> [reason]
  punishments:
    description: Gives you a list of all punishments
    usage: /<command>